-- begin SALESSAAS_CATEGORY
create unique index IDX_SALESSAAS_CATEGORY_UNIQ_CATEGORY_NAME on SALESSAAS_CATEGORY (CATEGORY_NAME) ^
-- end SALESSAAS_CATEGORY
-- begin SALESSAAS_ORDER
alter table SALESSAAS_ORDER add constraint FK_SALESSAAS_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references SALESSAAS_CUSTOMER(ID)^
alter table SALESSAAS_ORDER add constraint FK_SALESSAAS_ORDER_ON_TYPE foreign key (TYPE_ID) references SALESSAAS_JOB_TYPE(ID)^
alter table SALESSAAS_ORDER add constraint FK_SALESSAAS_ORDER_ON_SEASON foreign key (SEASON_ID) references SALESSAAS_YEAR(ID)^
alter table SALESSAAS_ORDER add constraint FK_SALESSAAS_ORDER_ON_SALES_PERSON foreign key (SALES_PERSON_ID) references SALESSAAS_SALES_PERSON(ID)^
alter table SALESSAAS_ORDER add constraint FK_SALESSAAS_ORDER_ON_SOURCE foreign key (SOURCE_ID) references SALESSAAS_SOURCE(ID)^
create index IDX_SALESSAAS_ORDER_ON_CUSTOMER on SALESSAAS_ORDER (CUSTOMER_ID)^
create index IDX_SALESSAAS_ORDER_ON_TYPE on SALESSAAS_ORDER (TYPE_ID)^
create index IDX_SALESSAAS_ORDER_ON_SEASON on SALESSAAS_ORDER (SEASON_ID)^
create index IDX_SALESSAAS_ORDER_ON_SALES_PERSON on SALESSAAS_ORDER (SALES_PERSON_ID)^
create index IDX_SALESSAAS_ORDER_ON_SOURCE on SALESSAAS_ORDER (SOURCE_ID)^
-- end SALESSAAS_ORDER
-- begin SALESSAAS_JOB_TYPE
create unique index IDX_SALESSAAS_JOB_TYPE_UNIQ_TYPE_NAME on SALESSAAS_JOB_TYPE (TYPE_NAME) ^
-- end SALESSAAS_JOB_TYPE
-- begin SALESSAAS_SALES_PERSON
create unique index IDX_SALESSAAS_SALES_PERSON_UNIQ_SALES_PERSON_NAME on SALESSAAS_SALES_PERSON (SALES_PERSON_NAME) ^
-- end SALESSAAS_SALES_PERSON
-- begin SALESSAAS_ORDER_ITEM
alter table SALESSAAS_ORDER_ITEM add constraint FK_SALESSAAS_ORDER_ITEM_ON_ORDER foreign key (ORDER_ID) references SALESSAAS_ORDER(ID)^
alter table SALESSAAS_ORDER_ITEM add constraint FK_SALESSAAS_ORDER_ITEM_ON_PRODUCT foreign key (PRODUCT_ID) references SALESSAAS_PRODUCT(ID)^
create index IDX_SALESSAAS_ORDER_ITEM_ON_ORDER on SALESSAAS_ORDER_ITEM (ORDER_ID)^
create index IDX_SALESSAAS_ORDER_ITEM_ON_PRODUCT on SALESSAAS_ORDER_ITEM (PRODUCT_ID)^
-- end SALESSAAS_ORDER_ITEM
-- begin SALESSAAS_PRODUCT
alter table SALESSAAS_PRODUCT add constraint FK_SALESSAAS_PRODUCT_ON_CATEGORY foreign key (CATEGORY_ID) references SALESSAAS_CATEGORY(ID)^
create unique index IDX_SALESSAAS_PRODUCT_UNIQ_PRODUCT_CODE on SALESSAAS_PRODUCT (PRODUCT_CODE) ^
create index IDX_SALESSAAS_PRODUCT_ON_CATEGORY on SALESSAAS_PRODUCT (CATEGORY_ID)^
-- end SALESSAAS_PRODUCT

-- begin SALESSAAS_COMPANY
alter table SALESSAAS_COMPANY add constraint FK_SALESSAAS_COMPANY_ON_LOGO_FILE foreign key (LOGO_FILE_ID) references SYS_FILE(ID)^
create index IDX_SALESSAAS_COMPANY_ON_LOGO_FILE on SALESSAAS_COMPANY (LOGO_FILE_ID)^
-- end SALESSAAS_COMPANY
