alter table SALESSAAS_CUSTOMER add constraint FK_SALESSAAS_CUSTOMER_ON_LOGO_FILE foreign key (LOGO_FILE_ID) references SYS_FILE(ID);
create index IDX_SALESSAAS_CUSTOMER_ON_LOGO_FILE on SALESSAAS_CUSTOMER (LOGO_FILE_ID);
