alter table SALESSAAS_COMPANY add constraint FK_SALESSAAS_COMPANY_ON_LOGO_FILE foreign key (LOGO_FILE_ID) references SYS_FILE(ID);
create index IDX_SALESSAAS_COMPANY_ON_LOGO_FILE on SALESSAAS_COMPANY (LOGO_FILE_ID);
