alter table SALESSAAS_ORDER_ITEM add constraint FK_SALESSAAS_ORDER_ITEM_ON_ORDER foreign key (ORDER_ID) references SALESSAAS_ORDER(ID);
alter table SALESSAAS_ORDER_ITEM add constraint FK_SALESSAAS_ORDER_ITEM_ON_PRODUCT foreign key (PRODUCT_ID) references SALESSAAS_PRODUCT(ID);
create index IDX_SALESSAAS_ORDER_ITEM_ON_ORDER on SALESSAAS_ORDER_ITEM (ORDER_ID);
create index IDX_SALESSAAS_ORDER_ITEM_ON_PRODUCT on SALESSAAS_ORDER_ITEM (PRODUCT_ID);
