alter table SALESSAAS_PRODUCT add constraint FK_SALESSAAS_PRODUCT_ON_CATEGORY foreign key (CATEGORY_ID) references SALESSAAS_CATEGORY(ID);
create unique index IDX_SALESSAAS_PRODUCT_UNIQ_PRODUCT_CODE on SALESSAAS_PRODUCT (PRODUCT_CODE) ;
create index IDX_SALESSAAS_PRODUCT_ON_CATEGORY on SALESSAAS_PRODUCT (CATEGORY_ID);
