alter table SALESSAAS_ORDER add constraint FK_SALESSAAS_ORDER_ON_SEASON foreign key (SEASON_ID) references SALESSAAS_YEAR(ID);
create index IDX_SALESSAAS_ORDER_ON_SEASON on SALESSAAS_ORDER (SEASON_ID);
