alter table SALESSAAS_ORDER add constraint FK_SALESSAAS_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references SALESSAAS_CUSTOMER(ID);
alter table SALESSAAS_ORDER add constraint FK_SALESSAAS_ORDER_ON_TYPE foreign key (TYPE_ID) references SALESSAAS_JOB_TYPE(ID);
alter table SALESSAAS_ORDER add constraint FK_SALESSAAS_ORDER_ON_SALES_PERSON foreign key (SALES_PERSON_ID) references SALESSAAS_SALES_PERSON(ID);
create index IDX_SALESSAAS_ORDER_ON_CUSTOMER on SALESSAAS_ORDER (CUSTOMER_ID);
create index IDX_SALESSAAS_ORDER_ON_TYPE on SALESSAAS_ORDER (TYPE_ID);
create index IDX_SALESSAAS_ORDER_ON_SALES_PERSON on SALESSAAS_ORDER (SALES_PERSON_ID);
